// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, user_id, url, title) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, title, url, user_id, last_fetched_at
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	Url       sql.NullString
	Title     sql.NullString
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Url,
		arg.Title,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted_feed_follow as (
    INSERT INTO feed_follows (id, feed_id, user_id, created_at, updated_at) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    RETURNING id, feed_id, user_id, created_at, updated_at
)
SELECT feeds.title, users.name as username 
FROM inserted_feed_follow 
INNER JOIN users ON users.id = inserted_feed_follow.user_id
INNER JOIN feeds ON feeds.id = inserted_feed_follow.feed_id
LIMIT 1
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	FeedID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateFeedFollowRow struct {
	Title    sql.NullString
	Username sql.NullString
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.FeedID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateFeedFollowRow
	err := row.Scan(&i.Title, &i.Username)
	return i, err
}

const getFeed = `-- name: GetFeed :one
SELECT id, created_at, updated_at, title, url, user_id, last_fetched_at FROM feeds WHERE url = $1 LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, url sql.NullString) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT f.id, f.created_at, f.updated_at, f.title, f.url, f.user_id, f.last_fetched_at, u.name as username FROM feeds as f JOIN users as u on u.id = f.user_id
`

type GetFeedsRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         sql.NullString
	Url           sql.NullString
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
	Username      sql.NullString
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.UserID,
			&i.LastFetchedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyFeeds = `-- name: GetMyFeeds :many
SELECT feeds.title, users.name FROM feed_follows 
INNER JOIN feeds ON feeds.id = feed_follows.feed_id
INNER JOIN users ON users.id = feed_follows.user_id
WHERE feed_follows.user_id = $1
`

type GetMyFeedsRow struct {
	Title sql.NullString
	Name  sql.NullString
}

func (q *Queries) GetMyFeeds(ctx context.Context, userID uuid.UUID) ([]GetMyFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMyFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyFeedsRow
	for rows.Next() {
		var i GetMyFeedsRow
		if err := rows.Scan(&i.Title, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT id, created_at, updated_at, title, url, user_id, last_fetched_at FROM feeds WHERE last_fetched_at IS NULL OR last_fetched_at < $1
ORDER BY last_fetched_at ASC LIMIT 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context, lastFetchedAt sql.NullTime) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch, lastFetchedAt)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}

const markFeedFetched = `-- name: MarkFeedFetched :exec
UPDATE feeds SET last_fetched_at = $1 WHERE url = $2
`

type MarkFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	Url           sql.NullString
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetched, arg.LastFetchedAt, arg.Url)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM feed_follows WHERE feed_follows.user_id = $1 AND feed_follows.feed_id = (
    SELECT feeds.id FROM feeds WHERE feeds.url = $2 LIMIT 1
)
`

type UnfollowParams struct {
	UserID uuid.UUID
	Url    sql.NullString
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.UserID, arg.Url)
	return err
}
